header:
  version: 13

distro: poky

repos:
  poky:
    url: https://git.yoctoproject.org/git/poky
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

local_conf_header:
  enable-systemd: |
    INIT_MANAGER:poky = "systemd"
